title: 难易的技术博客
description: 记录一些技术学习实践的笔记
lang: zh-CN
timezone: Asia/Shanghai

permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true

# GitHub Pages supported theme
theme: just-the-docs

# Defaults
defaults:
  - _posts:
      layout: post
